# [ETRADE2]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [ETRADE2]    Script Date: 14.08.2023 01:13:24 ******/
CREATE DATABASE [ETRADE2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ETRADE2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ETRADE2.mdf' , SIZE = 224256KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ETRADE2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ETRADE2_log.ldf' , SIZE = 2304KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ETRADE2] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ETRADE2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ETRADE2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ETRADE2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ETRADE2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ETRADE2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ETRADE2] SET ARITHABORT OFF 
GO
ALTER DATABASE [ETRADE2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ETRADE2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ETRADE2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ETRADE2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ETRADE2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ETRADE2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ETRADE2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ETRADE2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ETRADE2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ETRADE2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ETRADE2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ETRADE2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ETRADE2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ETRADE2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ETRADE2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ETRADE2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ETRADE2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ETRADE2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ETRADE2] SET  MULTI_USER 
GO
ALTER DATABASE [ETRADE2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ETRADE2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ETRADE2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ETRADE2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ETRADE2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ETRADE2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ETRADE2] SET QUERY_STORE = OFF
GO

# [dbo].[ADDRES]

In [0]:
USE [ETRADE2]
GO

In [0]:
/****** Object:  Table [dbo].[ADDRES]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADDRES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[ADDRESSTYPE] [tinyint] NULL,
	[COUNTRYID] [int] NULL,
	[CITYID] [int] NULL,
	[TOWNID] [int] NULL,
	[DISTRICTID] [int] NULL,
	[POSTALCODE] [varchar](20) NULL,
	[ADDRESSTEXT] [varchar](500) NULL,
 CONSTRAINT [PK__ADDRES__3214EC2783B70F6F] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[BASKET]

In [0]:
/****** Object:  Table [dbo].[BASKET]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BASKET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[CREATEDDATE] [smalldatetime] NULL,
	[LASTMODIFIEDDATE] [smalldatetime] NULL,
	[STATUS_] [smallint] NULL,
 CONSTRAINT [PK__BASKET__3214EC277DE6EED1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[BASKETDETAIL]

In [0]:
/****** Object:  Table [dbo].[BASKETDETAIL]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BASKETDETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BASKETID] [int] NULL,
	[DATE_] [smalldatetime] NULL,
	[ITEMID] [int] NULL,
	[AMOUNT] [float] NULL,
	[PRICE] [float] NULL,
	[TOTAL] [float] NULL,
 CONSTRAINT [PK__BASKETDE__3214EC277331258C] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[CITY]

In [0]:
/****** Object:  Table [dbo].[CITY]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CITY] [varchar](100) NULL,
 CONSTRAINT [PK__CITY__3214EC2705CDD5EE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[COUNTRY]

In [0]:
/****** Object:  Table [dbo].[COUNTRY]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COUNTRY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTRY] [varchar](100) NULL,
 CONSTRAINT [PK__COUNTRY__3214EC27ACB6B5AD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DISTRICT]

In [0]:
/****** Object:  Table [dbo].[DISTRICT]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISTRICT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TOWNID] [int] NULL,
	[DISTRICT] [varchar](100) NULL,
 CONSTRAINT [PK__DISTRICT__3214EC277E09C8C5] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DISTRICT_STREET]

In [0]:
/****** Object:  Table [dbo].[DISTRICT_STREET]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISTRICT_STREET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ILKODU] [float] NULL,
	[ILCEKODU] [float] NULL,
	[BELDEKODU] [nvarchar](255) NULL,
	[MAHALLEKODU] [float] NULL,
	[ILADI] [nvarchar](255) NULL,
	[ILCEADI] [nvarchar](255) NULL,
	[BELDEADI] [nvarchar](255) NULL,
	[MAHALLEADI] [nvarchar](255) NULL,
	[CADDESOKAK] [nvarchar](255) NULL,
 CONSTRAINT [PK__DISTRICT__3214EC27F2032904] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[INVOICE]

In [0]:
/****** Object:  Table [dbo].[INVOICE]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDERID] [int] NULL,
	[INVOICENO] [varchar](50) NULL,
	[DATE_] [smalldatetime] NULL,
	[CARGOFICHENO] [varchar](50) NULL,
	[STATUS_] [int] NULL,
 CONSTRAINT [PK__INVOICE__3214EC27BE865564] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[INVOICEDETAIL]

In [0]:
/****** Object:  Table [dbo].[INVOICEDETAIL]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICEDETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICEID] [int] NULL,
	[ORDERDETAILID] [int] NULL,
	[ITEMID] [int] NULL,
	[PRICE] [float] NULL,
	[AMOUNT] [float] NULL,
	[TOTALPRICE] [float] NULL,
 CONSTRAINT [PK__INVOICED__3214EC27B3207392] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ITEM]

In [0]:
/****** Object:  Table [dbo].[ITEM]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEMCODE] [varchar](20) NULL,
	[ITEMNAME] [varchar](100) NULL,
	[PRICE] [float] NULL,
	[CATEGORY1] [varchar](50) NULL,
	[CATEGORY2] [varchar](50) NULL,
	[CATEGORY3] [varchar](50) NULL,
 CONSTRAINT [PK__ITEM__3214EC2703584B70] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ITEMCATEGORY]

In [0]:
/****** Object:  Table [dbo].[ITEMCATEGORY]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEMCATEGORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORYNAME] [int] NULL,
 CONSTRAINT [PK__ITEMCATE__3214EC277C95F623] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ORDER_]

In [0]:
/****** Object:  Table [dbo].[ORDER_]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER_](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[ADDRESSID] [int] NULL,
	[BASKETID] [int] NULL,
	[DATE_] [smalldatetime] NULL,
	[STATUS_] [smallint] NULL,
 CONSTRAINT [PK__ORDER___3214EC275C551D54] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ORDERDETAIL]

In [0]:
/****** Object:  Table [dbo].[ORDERDETAIL]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERDETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDERID] [int] NULL,
	[BASKETDETAILID] [int] NULL,
	[ITEMID] [int] NULL,
	[AMOUNT] [float] NULL,
	[PRICE] [float] NULL,
	[TOTALPRICE] [float] NULL,
 CONSTRAINT [PK__ORDERDET__3214EC2791C3D8E2] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[PasswordList]

In [0]:
/****** Object:  Table [dbo].[PasswordList]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PasswordList](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PASSWORD_] [varchar](50) NULL,
 CONSTRAINT [PK__Password__3214EC272D2A12D1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[PAYMENT]

In [0]:
/****** Object:  Table [dbo].[PAYMENT]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BASKETID] [int] NULL,
	[TOTALPRICE] [float] NULL,
	[PAYMENTTYPE] [int] NULL,
	[DATE_] [smalldatetime] NULL,
	[ISOK] [bit] NULL,
	[APPROVECODE] [varchar](20) NULL,
	[ERROR_] [varchar](1000) NULL,
 CONSTRAINT [PK__PAYMENT__3214EC2714BC3A9F] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TOWN]

In [0]:
/****** Object:  Table [dbo].[TOWN]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOWN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CITYID] [int] NULL,
	[TOWN] [varchar](100) NULL,
 CONSTRAINT [PK__TOWN__3214EC27247F34C9] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[USER_]

In [0]:
/****** Object:  Table [dbo].[USER_]    Script Date: 14.08.2023 01:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME_] [varchar](50) NULL,
	[PASSWORD_] [varchar](50) NULL,
	[NAMESURNAME] [varchar](100) NULL,
	[EMAIL] [varchar](100) NULL,
	[GENDER] [varchar](1) NULL,
	[CREATEDDATE] [smalldatetime] NULL,
	[BIRTHDATE] [date] NULL,
	[TELNR1] [varchar](15) NULL,
	[TELNR2] [varchar](15) NULL,
 CONSTRAINT [PK__USER___3214EC27C89EF92F] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [ETRADE2]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [ETRADE2] SET  READ_WRITE 
GO